version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - 8080:80
      # - 80:8080
      - 8080:8080
    networks:
      - lumen-8
    # command: php -S 0.0.0.0:8080 public/index.php
networks:
    lumen-8:
        driver: bridge
